# Generated by Django 4.1.7 on 2023-02-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAndVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_video_title', models.CharField(max_length=50)),
                ('image_video', models.ImageField(upload_to='images_videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
